import { runParticlesDemo } from '../shared/particlesShared'
await runParticlesDemo({
  title: 'Particles 2D',
  mode: 'plane2d',
  particleSize: 80,
  cameraZ: 5.2,
  defaults: {
    splatRadius: 10,
    splatForce: 6,
    pressureIterations: 8,
    curlStrength: 0.2,
    velocityDissipation: 0.992,
    densityDissipation: 0.9,
    pressureDissipation: 0.8,
    enableVorticity: false,
    bfecc: true,
    reflectWalls: true,
    flowStrength: 1.0,
    depthLift: 0,
    flowThreshold: 40,
    maxFlowSpeed: 20,
    responseGamma: 4,
    perpendicularAngle: 0,
    sideVariation: 0,
    depthAttenuationScale: 1,
    spring: 4.0,
    zeta: 1.15,
    dragLin: 0.28,
    dragQuad: 0.05,
    aMax: 24,
    vMaxScale: 1,
    pointSize: 6,
    rotationSpeed: 0.07,
  },
})
