import { type Renderer, type Texture } from 'three/webgpu';
import type { TextureNode } from 'three/webgpu';
import { type FluidSimulationOptions, type FluidSplatOptions, type IFluidSimulation } from './types.js';
export declare class WGSLFluidSimulation implements IFluidSimulation {
    readonly simResolution: number;
    readonly dyeResolution: number;
    pressureIterations: number;
    densityDissipation: number;
    velocityDissipation: number;
    pressureDissipation: number;
    curlStrength: number;
    splatRadius: number;
    splatForce: number;
    baseDelta: number;
    enableVorticity: boolean;
    bfecc: boolean;
    reflectWalls: boolean;
    enableDye: boolean;
    dyeDissipation: number;
    readonly densityNode: TextureNode;
    readonly dyeNode: TextureNode;
    readonly velocityNode: TextureNode;
    readonly pressureNode: TextureNode;
    readonly divergenceNode: TextureNode;
    readonly curlNode: TextureNode;
    private readonly renderer;
    private readonly backend;
    private readonly device;
    private readonly velocity;
    private readonly density;
    private readonly dye;
    private readonly pressure;
    private readonly divergence;
    private readonly curl;
    private readonly pipelines;
    private readonly linearSampler;
    private readonly uniformBuffers;
    private readonly textureViews;
    private readonly bindGroups;
    private readonly splats;
    private frameUniformIndex;
    private targetsNeedClear;
    private viewportWidth;
    private viewportHeight;
    private simWidth;
    private simHeight;
    private dyeWidth;
    private dyeHeight;
    constructor(renderer: Renderer, options?: FluidSimulationOptions);
    get velocityTexture(): Texture;
    get velocityProjectedTexture(): Texture;
    get densityTexture(): Texture;
    get dyeTexture(): Texture;
    resize(width: number, height: number): void;
    addSplat(x: number, y: number, dx: number, dy: number, options?: FluidSplatOptions): void;
    step(deltaSeconds: number): void;
    dispose(): void;
    private getWebGPUBackend;
    private createPipelines;
    private initGpuTextures;
    private allTextures;
    private getGpuTexture;
    private getTextureView;
    private writeUniform;
    private getBindGroup;
    private dispatch;
    private clearTargets;
    private clearTexture;
    private applySplat;
    private applySplatToDouble;
    private advectTexture;
    private refreshPublicNodes;
}
