import { runParticlesDemo } from '../shared/particlesShared'

await runParticlesDemo({
  title: 'Particles 3D',
  mode: 'cloud3d',
  particleSize: 64,
  cameraZ: 6.4,
  defaults: {
    splatRadius: 10,
    splatForce: 6,
    pressureIterations: 8,
    curlStrength: 0.05,
    velocityDissipation: 0.992,
    densityDissipation: 0.9,
    pressureDissipation: 0.8,
    enableVorticity: false,
    bfecc: true,
    reflectWalls: true,
    flowStrength: 1.05,
    depthLift: 0.95,
    flowThreshold: 50,
    maxFlowSpeed: 12,
    responseGamma: 4,
    perpendicularAngle: 1.25,
    sideVariation: 1,
    depthAttenuationScale: 2,
    spring: 4.0,
    zeta: 1.15,
    dragLin: 0.28,
    dragQuad: 0.05,
    aMax: 24,
    vMaxScale: 1,
    pointSize: 10,
    rotationSpeed: 0.07,
  },
})
